enum Permission {
    MOBILE_DASHBOARD_PAGE_VIEW = 'MOBILE_DASHBOARD_PAGE_VIEW',
    MOBILE_DASHBOARD_PAGE_EDIT = 'MOBILE_DASHBOARD_PAGE_EDIT',
    // MAD_ADMIN_CONFIGS_WRITE = 'MAD_ADMIN_CONFIGS_WRITE', // To save tenant level configuration
    // MIND_DASHBOARD_PAGE_VIEW = 'MIND_DASHBOARD_PAGE_VIEW',
    // MIND_PURCHASE_ORDER_VIEW = 'MIND_PURCHASE_ORDER_VIEW',
    // MIND_PURCHASE_ORDER_EDIT = 'MIND_PURCHASE_ORDER_EDIT',
    // MIND_INTEGRATION_CONFIG_READ = 'MIND_INTEGRATION_CONFIG_READ',
    // MIND_PURCHASE_ORDER_DEPARTMENT_VIEW = 'MIND_PURCHASE_ORDER_DEPARTMENT_VIEW',
    // MIND_PURCHASE_ORDER_DEPARTMENT_EDIT = 'MIND_PURCHASE_ORDER_DEPARTMENT_EDIT',
    // MIND_TENANT_PARAMETERS_SETUP = 'MIND_TENANT_PARAMETERS_SETUP'
  }
  
  export default Permission
  